export const IS_DEMO_MODE = true; // Toggle this to false to remove mock data

export const DEMO_INCIDENTS = [
  {
    id: 'demo-inc-1',
    category: 'Theft',
    description: 'Chain snatching reported near Andheri Railway Station. Two individuals on a black motorcycle.',
    urgency: 'high',
    status: 'assigned',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    citizen_id: 'citizen-1',
    priority_score: 4,
    ml_priority_suggestion: 'High probability of repeat offense.',
    assigned_officer_id: 'officer-1',
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    is_emergency: false,
    city: 'Mumbai',
    area: 'Andheri West',
    evidence_urls: [],
    close_reason: null,
    assigned_higher_officer_id: null,
  },
  {
    id: 'demo-inc-2',
    category: 'Harassment',
    description: 'Group of men passing lewd comments near NM College gate. Occurring past 3 days.',
    urgency: 'medium',
    status: 'in_progress',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    citizen_id: 'citizen-2',
    priority_score: 3,
    ml_priority_suggestion: 'Moderate risk. Pattern detected across 2 other reports.',
    assigned_officer_id: 'officer-2',
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    is_emergency: false,
    city: 'Mumbai',
    area: 'Vile Parle',
    evidence_urls: [],
    close_reason: null,
    assigned_higher_officer_id: null,
  },
  {
    id: 'demo-inc-3',
    category: 'Unsafe Area',
    description: 'Streetlights broken in isolated lane behind shopping mall. Highly unsafe after 8 PM.',
    urgency: 'low',
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    citizen_id: 'citizen-3',
    priority_score: 1,
    ml_priority_suggestion: 'Infrastructure issue. Route to civil authorities.',
    assigned_officer_id: null,
    deadline: null,
    is_emergency: false,
    city: 'Mumbai',
    area: 'Bandra',
    evidence_urls: [],
    close_reason: null,
    assigned_higher_officer_id: null,
  },
  {
    id: 'demo-inc-4',
    category: 'Accident',
    description: 'Severe multi-vehicle collision on Western Express Highway. Medical assistance needed urgently.',
    urgency: 'critical',
    status: 'resolved',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    citizen_id: 'citizen-4',
    priority_score: 5,
    ml_priority_suggestion: 'Life-threatening tier. Auto-escalated to Traffic & Medical.',
    assigned_officer_id: 'officer-3',
    deadline: null,
    is_emergency: true,
    city: 'Mumbai',
    area: 'Goregaon',
    evidence_urls: [],
    close_reason: 'Area cleared. Standard protocol executed.',
    assigned_higher_officer_id: null,
  }
];

export const DEMO_MISSING_ITEMS = [
  {
    id: 'demo-miss-1',
    item_name: 'Red Travel Backpack',
    category: 'Bag/Luggage',
    color: 'Red',
    brand: 'Real Bag',
    last_seen_location: 'Platform 4, CST Station',
    found_location: 'Mumbai Central Terminus',
    date_reported: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    description: 'Found a red "Real Bag" brand backpack on a bench.',
    status: 'found',
    city: 'Mumbai',
    area: 'Central',
    image_url: '/red_backpack.jpg',
  },
  {
    id: 'demo-miss-2',
    item_name: 'Gold Bracelet',
    category: 'Jewelry',
    color: 'Gold',
    brand: 'Tanishq',
    last_seen_location: null,
    found_location: 'Outside Phoenix Mall Entry Gate',
    date_reported: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    description: 'Found a 22k gold bracelet with a floral pattern.',
    status: 'found',
    city: 'Mumbai',
    area: 'Lower Parel',
    image_url: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'demo-miss-3',
    item_name: 'Blue Leather Wallet',
    category: 'Accessories',
    color: 'Navy Blue',
    brand: 'Tommy Hilfiger',
    last_seen_location: 'Near Mithibai College',
    found_location: 'Handed over to Juhu Police Station',
    date_reported: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    description: 'Contains PAN card, Aadhar, and some cash.',
    status: 'claimed',
    city: 'Mumbai',
    area: 'Juhu',
    image_url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'demo-miss-4',
    item_name: 'Realme GT Smartphone',
    category: 'Electronics',
    color: 'Mint Green',
    brand: 'Realme',
    last_seen_location: null,
    found_location: 'Bus Stop outside Dadar Station',
    date_reported: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    description: 'Mint green smartphone found in locked state.',
    status: 'found',
    city: 'Mumbai',
    area: 'Dadar',
    image_url: '/silver_watch.jpg',
  },
  {
    id: 'demo-miss-5',
    item_name: 'Silver Wrist Watch',
    claim_ref: 'CLM-90231',
    category: 'Accessories',
    color: 'Silver',
    brand: 'Analog',
    last_seen_location: null,
    found_location: 'Bandra West',
    date_reported: new Date().toISOString(),
    description: 'Analog silver watch with black dial and metal strap.',
    status: 'found',
    city: 'Mumbai',
    area: 'Bandra',
    image_url: '/silver_watch.jpg',
  },
  {
    id: 'demo-miss-6',
    item_name: 'White Yamaha Scooter',
    category: 'Vehicles',
    color: 'White',
    brand: 'Yamaha',
    last_seen_location: null,
    found_location: 'Juhu Tara Road',
    date_reported: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    description: 'White Yamaha Fascino scooter found with keys in ignition.',
    status: 'found',
    city: 'Mumbai',
    area: 'Juhu',
    image_url: '/white_scooter.jpg',
  }
];

export const DEMO_USERS = [
  {
    id: 'demo-u-1',
    user_id: 'uuid-1',
    role: 'citizen',
    is_approved: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    profile: { full_name: 'Rahul Sharma' }
  },
  {
    id: 'demo-u-2',
    user_id: 'uuid-2',
    role: 'field_police',
    is_approved: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    profile: { full_name: 'Inspector Vikram Singh' }
  },
  {
    id: 'demo-u-3',
    user_id: 'uuid-3',
    role: 'higher_officer',
    is_approved: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    profile: { full_name: 'DCP Anjali Desai' }
  },
  {
    id: 'demo-u-4',
    user_id: 'uuid-4',
    role: 'field_police',
    is_approved: false,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    profile: { full_name: 'Sub-Inspector Karan Verma' }
  }
];

export const DEMO_AUDIT_LOGS = [
  {
    id: 'demo-aud-1',
    actor_id: 'uuid-3',
    action: 'case_assigned',
    details: { officer_id: 'uuid-2', deadline: '2026-03-31', notes: 'Immediate dispatch required.' },
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    incident_id: 'demo-inc-1'
  },
  {
    id: 'demo-aud-2',
    actor_id: 'uuid-admin',
    action: 'user_approved',
    details: { approved_user_id: 'uuid-2', role: 'field_police' },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    incident_id: null
  },
  {
    id: 'demo-aud-3',
    actor_id: 'uuid-2',
    action: 'daily_update',
    details: { update_text: 'Arrived at scene. Reviewing CCTV.', status_change: 'in_progress' },
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    incident_id: 'demo-inc-2'
  },
  {
    id: 'demo-aud-4',
    actor_id: 'system',
    action: 'sos_triggered',
    details: { location: 'Goregaon', auto_assigned: true },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    incident_id: 'demo-inc-4'
  }
];
